trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    git config --local user.name "serverfiles-update"
    git config --local user.email "info@biolab.si"
    git checkout -b serverfiles_update_$(date +"%Y/%m/%d")
    echo "it works $(date +%Y/%m/%d)" > test.txt
    git add .
    git commit -m "Serverfiles update [skip ci]"
  displayName: 'Commit updated files'

- task: DownloadSecureFile@1
  name: deploy_key
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'

- script: |
    echo Installing $(deploy_key.secureFilePath) ...
    mkdir ~/.ssh && mv $(deploy_key.secureFilePath) ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    git remote set-url --push origin git@github.com:JakaKokosar/bioinformatics-serverfiles.git
    # hub pull-request --base jakakokosar:master --head jakakokosar:test_autoupdates
    git push origin -u HEAD:serverfiles_update_$(date +"%Y/%m/%d")
  displayName: 'Push to origin'
  # condition: |
  #   and(not(eq(variables['Build.Reason'], 'PullRequest')),
  #       eq(variables['Build.SourceBranch'], 'refs/heads/test_autoupdates')) 