trigger:
  - master

# no PR builds
pr: none

jobs:

- job: prepare_serverfiles
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: python -m pip install --upgrade pip setuptools wheel numpy
      displayName: 'Install build tools'

    - script: |
        python -m pip install --upgrade pip pyqt5 orange3 plumbum serverfiles sqlite_utils https://github.com/jakakokosar/orange3-bioinformatics/archive/master.zip
      displayName: 'Install requirements'

    - script: |
        echo '$(Build.BuildId)'
        python prepare_serverfiles.py

    - task: CopyFiles@2
      condition: eq(variables['Agent.JobStatus'], 'Succeeded')
      inputs:
        contents: serverfiles_dump.tar.gz
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      condition: eq(variables['Agent.JobStatus'], 'Succeeded')
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)

    - script: |
        python handle_serverfiles_drop.py $(service.biolab.token) $(Build.BuildId)
