name: Prepare serverfiles

on:
  push:
    branches:
      - master

jobs:
  prepare_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools setuptools-scm wheel numpy
          pip install pyqt5 PyQtWebEngine orange3 plumbum serverfiles sqlite_utils
          pip install git+https://github.com/biolab/orange3-bioinformatics.git#egg=orange3-bioinformatics

      - name: Prepare serverfiles
        run: |
          python -u prepare_serverfiles.py

      - name: Transfer serverfiles_dump
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: 'serverfiles_dump.tar.gz'
          target: 'tmp'

      - name: Uncompress serverfiles_dump and cleanup
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            mkdir -p /srv/datasets/bioinformatics/v1/
            tar xzf ~/tmp/serverfiles_dump.tar.gz -C /srv/datasets/bioinformatics/v1/
            rm -r ~/tmp/
