name: Prepare serverfiles

on:
  push:
    branches:
      - master

jobs:
  prepare_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools setuptools-scm wheel numpy
          pip install pyqt5 PyQtWebEngine orange3 plumbum serverfiles sqlite_utils
          pip install git+https://github.com/biolab/orange3-bioinformatics.git#egg=orange3-bioinformatics

      - name: Prepare serverfiles
        run: |
          python -u prepare_serverfiles.py

      - uses: actions/upload-artifact@v1
        with:
          name: serverfiles_dump
          path: serverfiles/

  web_service_job:
    runs-on: ubuntu-latest
    needs: prepare_job
    steps:
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install requests
      - name: invoke orange-web-services
        run: |
          import requests

          resp = requests.get('https://api.github.com/repos/JakaKokosar/bioinformatics-serverfiles/actions/artifacts')
          resp2 = requests.get('https://api.github.com/repos/JakaKokosar/bioinformatics-serverfiles/actions/runs/${{ github.run_id }}/artifacts')

          print(resp.text)
          print()
          print(resp2.text)

          header = {'Authorization': 'Token ${{ secrets.SERVERFILES_SECRET_KEY }}'}
          url = 'https://service.biolab.si/serverfiles_update/bioinformatics/${{ github.run_id }}?version=v1'
          response = requests.get(url, headers=header)

          print(url)
          print(response.content)

          # Fail build if service.biolab.si unavailable
          response.raise_for_status()
        shell: python


# run: python -u invoke_web_service.py ${{ secrets.SERVERFILES_SECRET_KEY }} ${{ github.run_id }} v1
